# Generated by Django 2.0.5 on 2018-10-16 16:02

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('desc', models.CharField(max_length=200, verbose_name='个人简介')),
                ('desc_img', models.ImageField(upload_to='introduct/%Y/%m', verbose_name='简介图')),
                ('about_me', DjangoUeditor.models.UEditorField(default='', verbose_name='关于我')),
                ('company', models.CharField(max_length=20, verbose_name='就职公司')),
                ('project', models.CharField(max_length=20, verbose_name='个人项目')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('desc', models.CharField(max_length=500, verbose_name='从业经历')),
                ('img', models.ImageField(upload_to='company/%Y/%m', verbose_name='公司介绍图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduct.Introduct', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '从业经历',
                'verbose_name_plural': '从业经历',
            },
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('img', models.ImageField(upload_to='project/%Y/%m', verbose_name='项目图')),
                ('desc', models.CharField(max_length=100, verbose_name='项目介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduct.Introduct', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '个人项目',
                'verbose_name_plural': '个人项目',
            },
        ),
    ]
