# Generated by Django 2.0.5 on 2018-10-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='introduct',
            name='project',
        ),
    ]
