# Generated by Django 2.0.5 on 2018-10-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduct', '0002_auto_20181016_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='技术名称')),
                ('desc', models.CharField(max_length=200, verbose_name='简单介绍')),
                ('img', models.ImageField(upload_to='skill/%Y/%m', verbose_name='技能图标')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduct.Introduct', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '技术栈',
                'verbose_name_plural': '技术栈',
            },
        ),
        migrations.RemoveField(
            model_name='mycompany',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='myproject',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='项目介绍'),
        ),
        migrations.DeleteModel(
            name='MyCompany',
        ),
    ]
