# Generated by Django 2.0.5 on 2018-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180929_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('yx', '英雄高校'), ('dx', '大学个人')], default='yx', max_length=20, verbose_name='机构类别'),
        ),
    ]
